version: 'test-{build}'
environment:
  matrix:
    - nodejs_version: '10'
    - nodejs_version: '12'
    - nodejs_version: '14'
platform:
  - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
  - ps: 'Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform'
  - ps: '$NpmVersion = (npm -v).Substring(0,1)'
  - ps: 'if($NpmVersion -eq 5) { npm install -g npm@5 }'
  - ps: npm --version
  - npm install
  - ps: |-
      Invoke-WebRequest "https://dl.influxdata.com/influxdb/releases/influxdb-1.1.0_windows_amd64.zip" -OutFile .\influxdb-1.1.0_windows_amd64.zip;
      if (Test-Path .\influxdb-exe )
      {
          del .\influxdb-exe -Force -Recurse
      }
      md influxdb-exe;
      7z e .\influxdb-1.1.0_windows_amd64.zip -oinfluxdb-exe -r
      cd ".\influxdb-exe";
      $MyProcess = Start-Process influxd.exe -PassThru;
      cd ..
on_finish:
  - ps: Stop-Process -Id $MyProcess.Id
test_script:
  - echo %cd%
  - node --version
  - npm --version
  - ps: Start-Sleep -s 15
  - npm test
build: 'off'
